jupyter scripts

diff --git a/bin/open b/bin/open
--- a/bin/open
+++ b/bin/open
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 
-JUPYTER_URL=$(podman exec -it python-jupyter \
+CONATINER_NAME="jupy" 
+
+JUPYTER_URL=$(podman exec -it "$CONATINER_NAME" \
     jupyter notebook list \
     | grep http \
     | awk '{print $1}' \
@@ -11,13 +13,12 @@ if [ -z "$JUPYTER_URL" ]; then
     echo "error: Jupyter URL not found."
     exit 1
 else
-    echo "Jupyter URL: $JUPYTER_URL"
+    echo "Jupyter URL:"
+    echo "$JUPYTER_URL"; echo
     echo "Opening Jupyter Notebook in browser..."
-    xdg-open "$JUPYTER_URL" &> /dev/null
-    if [ $? -ne 0 ]; then
-        echo "error: failed to open browser."
+    if ! xdg-open "$JUPYTER_URL" &> /dev/null; then
+        echo "error: failed to open browser"
         exit 1
     fi
 fi
-
 
diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-CONTAINER_NAME="python-jupyter"
+CONTAINER_NAME="jupy"
 IMAGE_NAME="python-jupyter"
 
 # Require podman.
@@ -13,6 +13,7 @@ fi
 if ! podman ps -a --format "{{.Names}}" | grep -q "^${CONTAINER_NAME}$"; then
     echo "$CONTAINER_NAME: does not exist. Creating..."
     podman create \
+        --rm \
         --name "${CONTAINER_NAME}" \
         --volume "./scripts:/scripts" \
         -p 8888:8888 \
@@ -28,12 +29,16 @@ if ! podman ps --format "{{.Names}}" | grep -q "^${CONTAINER_NAME}$"; then
 fi
 
 echo "$CONTAINER_NAME: starting jupyter notebook..."
-if ! podman exec "${CONTAINER_NAME}" \
+# TODO: this says it fails when it doesn't fail.
+if ! podman exec -d "${CONTAINER_NAME}" \
     jupyter notebook \
         --ip=0.0.0.0 \
         --port=8888 \
         --no-browser \
-        --allow-root; then 
+        --allow-root & then 
     echo "error: failed to start jupyter notebook."
+else
+    echo "jupyter noteboot started!"
+    echo "run open.sh to access"
 fi
 
